# Generated by Django 5.2.1 on 2025-06-03 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('TODO', 'Pendiente de realizar'), ('EN_PROGRESO', 'En progreso'), ('HECHO', 'Realizado')], default='TODO', verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'db_table': 'tareas',
                'ordering': ['-id'],
            },
        ),
    ]
